# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }
inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.3.7
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'db/data_schema.rb'
    - 'db/data/*.rb'
    - 'db/migrate/*.rb'
    - 'config/**/*.rb'
    - 'node_modules/**/*'
    - 'bin/**/*'
    - 'lib/tasks/**/*.rake'
    - 'app/views/**/*.jbuilder'
    - 'vendor/**/*'

Naming/VariableNumber:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Layout/LineLength:
  Max: 100

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: false

Layout/SpaceAroundMethodCallOperator:
  Enabled: false

Lint/ConstantResolution:
  Enabled: false
  Ignore:
    - Test
    - EngineManagers

Lint/MissingSuper:
  Enabled: false

Lint/DeprecatedOpenSSLConstant:
  Enabled: false

Lint/MixedRegexpCaptureTypes:
  Enabled: false

Lint/RaiseException:
  Enabled: false

Lint/StructNewOverride:
  Enabled: false

Metrics/BlockLength:
  Max: 100
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - '**/*_spec.rb'
    - 'spec/**/*.rb'

RSpec/LetSetup:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/ImplicitSubject:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/ContextWording:
  Enabled: true
  Prefixes:
    - for
    - when
    - with
    - without
    - and

RSpec/VerifiedDoubleReference:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

Rails/UnknownEnv:
  Enabled: true
  Environments:
    - development
    - test
    - production
    - staging

RSpec/ImplicitBlockExpectation:
  Enabled: false

Style/ExponentialNotation:
  Enabled: false

Style/HashEachMethods:
  Enabled: false

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false

Style/RedundantFetchBlock:
  Enabled: false

Style/RedundantRegexpCharacterClass:
  Enabled: false

Style/RedundantRegexpEscape:
  Enabled: false

Style/SlicingWithRange:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes
# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false
